server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///leyou?characterEncoding=UTF-8
  redis:
    host: 127.0.0.1
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis-plus:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/xml/**Mapper.xml
ly:
  jwt:
    user:
      cookieName: LY_TOKEN # cookie名称
      cookieDomain: leyou.com # cookie的域
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
    wx:
      appID: wx8397f8696b538317
      mchID: 1473426802
      key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
      payType: NATIVE
      notifyUrl: http://f48t3j.natappfree.cc/api/pay/wx/notify