spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/shaoyingjie/leyou-config.git #这里要写自己的git地址
  rabbitmq:
    host: 192.168.157.129
    virtual-host: /leyou
    username: admin
    password: admin
server:
  port: 12000
management:  #暴露消息总线地址
  endpoints:
    web:
      exposure:
        include: bus-refresh