server:
  port: 10010
spring:
  application:
    name: ly-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 500
  ReadTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
zuul:
  prefix: /api
  routes:
      item-service: /item/**
      upload-service: /upload/**
      search-service: /search/**
      user-service: /user/**
      auth-service: /auth/**
      cart-service: /cart/**
      order-service:
            path: /order/**
            serviceId: order-service
            strip-prefix: false
      pay-service:
            path: /pay/**
            serviceId: order-service
            strip-prefix: false
  sensitive-headers:
ly:
  cors:
    addAllowedOrigin:
      - http://manage.leyou.com
      - http://www.leyou.com
    allowCredentials: true
    allowedHeaders:
      - "*"
    addAllowedMethod:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    maxAge: 360000
    filterPath: "/**"
  jwt:
    pubKeyPath: D:\workspace\leyou\ly-common\ssh\id_rsa.pub # 公钥地址
    user:
      cookieName: LY_TOKEN
  filter:
      allowPaths:
        - /api/auth/login
        - /api/search
        - /api/user/register
        - /api/user/check
        - /api/user/code
        - /api/item
        - /api/pay